### PR TITLE
Update the peru currency symbol 

### PR DESCRIPTION
**Pull request by guillaumeparis2000**
Update the peru currency symbol from `S/.` to `S/` as defined in the wikipedia: https://en.wikipedia.org/wiki/Peruvian_nuevo_sol

### CODE REVIEW

**Comment by zwacky** [comment]
https://en.wikipedia.org/wiki/Peruvian_sol says it's `S/.`, also http://www.xe.com/currency/pen-peruvian-sol says it's `S/.`. We should stick to those sources, ok?

**Comment by guillaumeparis2000** [comment]
`S/.` is for the peruvian sol and `S/` is for the new peruvian sol http://rpp.pe/lima/actualidad/bcr-este-es-el-nuevo-simbolo-monetario-del-sol-noticia-927124

**Comment by zwacky** [comment]
so basically it's updating the existing currency and nobody is using `S/.` anymore? i'm not very familiar with peruvian currency :(

**Comment by guillaumeparis2000** [comment]
Basically the article is saying that the new symbol `S/` is official from the 15 december of 2015 and must be used on new document emitted since this date. The old symbol is still valid until the 1st january 2017.

**Comment by zwacky** [comment]
alright, thanks for clarification!

**Comment by zwacky** [comment]
will publish this change the next days.

**Comment by guillaumeparis2000** [comment]
Thank you!

Add this link with the official documentation of Banco central de reserva de peru: http://www.bcrp.gob.pe/billetes-y-monedas.html

**Pull request merged**
