### PR TITLE
Add AED symbol

### PR DESCRIPTION
**Pull request by volkan-kalay**

### CODE REVIEW

**Comment by volkan-kalay** [comment]
Hello @zwacky ,
I hope you are well. Can you add AED symbol for us? 
Thanks a lot. 🙏🏻

**Comment by zwacky** [comment]
looks good, thank you @volkan-kalay

**Comment by volkan-kalay** [comment]
Thank you 🙏🏻

**Comment by zwacky** [comment]
FYI created 2.1.13 with this change (https://github.com/zwacky/isoCurrency/releases/tag/0.2.13)

**Comment by volkan-kalay** [comment]
Thanksss 💯

**Comment by volkan-kalay** [comment]
Hello again, 
We are usign via npm install command. But npm version is still 0.2.12 and we can't update. Can you release new version for us?  @zwacky

**Comment by zwacky** [comment]
Oops, you're right. I published it on npm now.
Haha sorry it's been a while since this package got an update 👍

**Pull request merged**
